image: python:3.9-slim

before_script:
  - pip3 install -r requirements.txt
  - apt-get update -qq && apt-get install -y -qq git && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

pages:
  stage: deploy
  script:
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - shared
